global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: romannumeral
    static_configs:
      - targets: 
        - romannumeral:8000